### PR TITLE
Reject invalid CAP inputs

### LINKED ISSUE #213: [PE-D][Tester D] Inconsistent behaviour detected in CAP
`add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 c/3.94fdsks/4.00 g/male u/Nanyang Polytechnic gd/05-2024 m/Computer Science ji/173296 jt/Software Engineer Intern t/rejected t/KIV` (CAP 3.94fdsks)

gets rejected by the system but

`add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 c/3.94f/4.00 g/male u/Nanyang Polytechnic gd/05-2024 m/Computer Science ji/173296 jt/Software Engineer Intern t/rejected t/KIV` (CAP 3.94f)

is accepted.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cheeheng/ped#5

### LINKED ISSUE #214: [PE-D][Tester C] Wrong error displayed for Invalid Inputs in CAP
I tried editing the CAP of some contacts (this problem probably applies for adding as well). 

When I run the following commands:
edit 1 c/10//11 
edit 1 c/0_0/::)
edit 1 c/1.1.1/2.2.2

This error is thrown: 
"CAPs should consist of a positive numeric value less than or equal to its maximum value, e.g. 4.0/5.0" - which is not the error in this case."

I believe the error thrown should be invalid format or something along those lines instead. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ReubenChay/ped#10

### LINKED ISSUE #220: [PE-D][Tester A] Users are allowed to add extra strings to CAP parameter by using `/`.
While the expected input for CAP is in the form `c/3.0/4.0`, the user can key in something like `c/3.0/4.0/5.0/yay`. This is just a minor bug since the program still grabs the input correctly, but might be something that the developers possibly lookout for.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Bubbl3T/ped#5

### LINKED ISSUE #242: Fix v1.3 bugs for Jessica

### PR DESCRIPTION
**Pull request by maryjess**
Now, invalid CAP inputs by definition are:
- Inputs that have multiple values e.g. `2/3/4/5` or `1.0/2.0/3.0`
- Inputs that contain alphabets e.g. `2.0f/3.0`
- Inputs that contain symbols e.g. `2#/4.0`

Changes made:
- Create validation regex for CAP that should only contain numeric characters, periods and spaces
- Apply validation regex for CAP upon parsing in `ParserUtil#parseCap()`
- Define new message constraint for CAPs containing invalid characters
- Add tests at `ParserUtilTest` and `CapTest`

Resolves #213
Resolves #214 
Resolves #220 
Resolves #242

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -196,18 +196,21 @@ public static Cap parseCap(String cap) throws ParseException {
...
             String[] capValues = trimmedCap.split(CAP_SEPARATOR);
-            double capValue;
-            double maximumCapValue;
-            capValue = Double.parseDouble(capValues[0]);
-            maximumCapValue = Double.parseDouble(capValues[1]);
+            if (!Cap.isValidCapFormat(capValues[0]) || !Cap.isValidCapFormat(capValues[1])) {
+                throw new ParseException(Cap.MESSAGE_NUMERIC_VALUE_REQUIRED);
+            } else if (capValues.length > 2) { // more than two values provided
+                throw new ParseException(Cap.MESSAGE_INVALID_CAP_FORMAT);
+            }
```
Comment (lulucopter) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:203]: Minor nitpick, feel u can refactor this whole portion out into a single method that throws a ParseException to improve code quality further

**Review by lulucopter — APPROVED** [review]
Other than some minor code quality nitpicks, LGTM.

**Review by JasonCP14 — APPROVED** [review]
